name: Build and Export iOS IPA

env:
  APP: ios-test

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform:
          - iOS
        xcode:
          - ^14
    runs-on: macos-10.15
    steps:
      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build
          code-coverage: true
          warnings-as-errors: true
          configuration: release